- hosts: localhost
  tasks:
    - name: Install Ansible Galaxy roles
      command: ansible-galaxy install -r requirements.yml

- name: Instalar agente zabbix con el rol
  hosts: all
  roles:
    - role: zabbix.zabbix.agent
      agent_variant: 2
      agent_major_version: 6.0
      agent_param_server: '127.0.0.1,172.27.10.37'         # address of Zabbix server to accept connections from;
      agent_param_serveractive: "{{ server_zabbix }}"   # address of Zabbix server to connect using active checks;
      agent_param_hostmetadata: '{{ group_names | join(",") }}'   # concatenate group list to the string;
      agent_param_hostinterfaceitem: 'system.hostname'
      agent_param_include: ["/opt/zabbix/zabbix_agent2.d/plugins.d/*.conf","/opt/zabbix/conf/*.conf"]
      agent_param_pidfile: "/opt/zabbix/zabbix_agent.pid"
      agent_param_logfile: "/opt/zabbix/zabbix_agent.log"
      agent_param_logfilesize: 1
      agent_param_hostinterfaceitem: 'system.hostname'

